// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvf-qZul3KJHI5z5quYkl3lEEBprSynZ8',
    appId: '1:825420618141:web:dd6ceb7114ee7e31a47774',
    messagingSenderId: '825420618141',
    projectId: 'skillsync-app-e7ae7',
    authDomain: 'skillsync-app-e7ae7.firebaseapp.com',
    storageBucket: 'skillsync-app-e7ae7.firebasestorage.app',
    measurementId: 'G-TVLB3SX4YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYJr1av-mAwYy7Clmc5ViQE0gyLxBcYiY',
    appId: '1:825420618141:android:4cb5dcd5ba3ca140a47774',
    messagingSenderId: '825420618141',
    projectId: 'skillsync-app-e7ae7',
    storageBucket: 'skillsync-app-e7ae7.firebasestorage.app',
  );
}
